// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpTvanoclU0eyoBGq0ZvOQnIsW8PH6S6w',
    appId: '1:966950404407:web:8294f92f91deaa024d1ab2',
    messagingSenderId: '966950404407',
    projectId: 'mensuration-tracker',
    authDomain: 'mensuration-tracker.firebaseapp.com',
    storageBucket: 'mensuration-tracker.firebasestorage.app',
    measurementId: 'G-021E892M49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNIxC_lMxxJZ3TihP9W_GKwaXV3vRbemM',
    appId: '1:966950404407:android:859aa83854204edc4d1ab2',
    messagingSenderId: '966950404407',
    projectId: 'mensuration-tracker',
    storageBucket: 'mensuration-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPhKPXGylSWVXlj35GTEdnoY2Ah_0XXs',
    appId: '1:966950404407:ios:e67ede8884766a914d1ab2',
    messagingSenderId: '966950404407',
    projectId: 'mensuration-tracker',
    storageBucket: 'mensuration-tracker.firebasestorage.app',
    iosClientId: '966950404407-635ckci9ndusgv60k5v544prpodcpabk.apps.googleusercontent.com',
    iosBundleId: 'com.anujkattel.mensurationtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwPhKPXGylSWVXlj35GTEdnoY2Ah_0XXs',
    appId: '1:966950404407:ios:dc954a3bce014b9f4d1ab2',
    messagingSenderId: '966950404407',
    projectId: 'mensuration-tracker',
    storageBucket: 'mensuration-tracker.firebasestorage.app',
    iosClientId: '966950404407-p3r07i59usv44s5t9e5vqf9bl4vh3a16.apps.googleusercontent.com',
    iosBundleId: 'com.example.mensurationhealthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpTvanoclU0eyoBGq0ZvOQnIsW8PH6S6w',
    appId: '1:966950404407:web:9e8ab519b26a83ca4d1ab2',
    messagingSenderId: '966950404407',
    projectId: 'mensuration-tracker',
    authDomain: 'mensuration-tracker.firebaseapp.com',
    storageBucket: 'mensuration-tracker.firebasestorage.app',
    measurementId: 'G-WNCV6PHMG8',
  );
}
